### PR TITLE
security: clear go/log-injection CodeQL FP alerts (Issue #2673)

### LINKED ISSUE #2673: security: clear go/log-injection CodeQL FP alerts (controller-api, reports-provider)
## Parent Epic
#2586 — CI performance / merge-queue throughput

## Goal
The standing open CodeQL `go/log-injection` alerts in `features/controller/api` and `features/reports/provider` are cleared to zero via source-level sanitization, so real findings aren't buried under a persistent FP backlog.

## Background
`go/log-injection` alerts are OPEN on develop — user-derived values (`steward_id`, `cluster`, job selectors, device IDs) logged as structured key-value fields through the JSON structured logger. Because the JSON encoder escapes field values, these are effectively false positives, but CodeQL's `go/log-injection` rule can't see the sink escapes and flags them anyway. One of these rode through PR #2623 (#2546) unclassified.

This story is Split B of #2632 (split by the Tech Lead 2026-07-13 review — the original story spanned 4 packages, over the 2-package ceiling). Split A (companion story, packages: `pkg/config` + `features/tenant`) covers the simpler sites and is recommended to land first — it has no `execErr`/struct-taint wrinkle and gives this story a proven, scan-confirmed fix commit to point at. This is not a hard code dependency; either story can verify independently via its own CodeQL scan.

## Alert locations (verified live 2026-07-13 against develop tip `17edc2cf`; re-query `gh api repos/cfg-is/cfgms/code-scanning/alerts?state=open` for the current list before starting — more may appear, some may have closed)
- `features/controller/api/handlers_jobs.go:77` (alert #1031)
- `features/controller/api/handlers_jobs.go:146` (alert #1032)
- `features/controller/api/handlers_workflows.go:411` (alert #1006)
- `features/controller/api/handlers_workflows.go:461` (alert #1011)
- `features/controller/api/handlers_workflows.go:490` (alert #1016)
- `features/reports/provider/provider.go:57` (alert #1056)

## Desired state
Every open `go/log-injection` alert at the six sites above is resolved by source-level sanitization of the user-derived value at the log site. Alerts clear on the next develop scan after the fix merges.

## Implementation Notes

**The exact recognized pattern — verified against live alert state, do not assume a shortcut works:**

CodeQL's `go/log-injection` query hardcodes its sanitizer (`ReplaceSanitizer` in upstream `LogInjectionCustomizations.qll`) as `strings.ReplaceAll(s, "\n"|"\r", ...)`. The confirmed-working shape, taken from `pkg/logging/sanitize.go:127-129` (`SanitizeLogValue`, fixed by PR #2292):

```go
s = strings.ReplaceAll(s, "\n", "_")
s = strings.ReplaceAll(s, "\r", "_")
```

i.e. **two sequential top-level reassignments of the same variable**, immediately in the same function as the log call. Two forms that look equivalent do **NOT** clear the alert — both are proven negative by the current live alert set (verified 2026-07-13):

1. **Calling `logging.SanitizeLogValue(x)` at the log-call site does NOT suppress the alert.** `features/reports/provider/provider.go:57` already does exactly this (`logging.SanitizeLogValue(deviceID)`) and is still open as alert #1056. PR #2292 fixed `SanitizeLogValue`'s own body to be CodeQL-legible, and explicitly *removed* the Models-as-Data summary model that used to mark the function's return as a barrier for callers — so the built-in `ReplaceSanitizer`'s intra-procedural pattern match does not propagate through the function-call boundary. Do not rely on delegating to `SanitizeLogValue`; inline the two-line `strings.ReplaceAll` sequence directly before/at the log call instead.
2. **A nested single-expression form does NOT suppress the alert either.** `features/controller/api/handlers_jobs.go:72` already has `safeSelector := strings.ReplaceAll(strings.ReplaceAll(req.Selector, "\n", ""), "\r", "")`, and the log calls that use `safeSelector` (line 77) and a captured `jobID` local (line 146, via the same enclosing function) are still open as alerts #1031/#1032. Use the sequential-reassignment form only, matching `sanitize.go` exactly — do not nest the two calls into one expression, and do not assume capturing a value into a fresh local earlier in the function is sufficient by itself.

**Required approach per site:** for each flagged value, add (or fix an existing broken attempt at) the exact two-line sequential-reassignment form immediately before the log call that uses it, then re-verify against a live scan (push to a branch/PR and check `gh api repos/cfg-is/cfgms/code-scanning/alerts?state=open` after the CodeQL run) rather than assuming any prior pattern in the codebase already works — two of the existing "already fixed-looking" sites above are proof that assumption is unsafe.

**`features/controller/api/handlers_jobs.go:146` needs investigation, not just re-sanitization:** the flagged value there is `jobID` (a fresh `uuid.New().String()`, not user input) logged alongside `execErr` from `executor.Execute(ctx, job)`. The real taint likely flows through `execErr` (the batch executor may embed `job.Selector` in an error/log message somewhere in its call chain) or via struct-field over-tainting (CodeQL treating other fields of the `job` struct as tainted once `job.Selector` is). Trace the actual flow with `find_referencing_symbols`/read before applying the two-line fix to the correct variable — sanitizing `jobID` again will not clear an alert whose real source is a different value.

**Which existing provider/central-provider guidance applies:** none — this is a source-hardening fix in existing feature code, not a new provider or central-provider extension. `pkg/logging.SanitizeLogValue` remains the correct sanitizer for actual security purposes (redaction, truncation, control-char stripping); the additional inline `strings.ReplaceAll` pair is purely to satisfy CodeQL's static pattern match and should be added in addition to (not instead of) real sanitization where a value isn't already sanitized for other reasons.

## Out of Scope
- The `pkg/config` and `features/tenant` sites (Split A, companion story).
- Other CodeQL rules (clear-text-logging etc.) unless they share the exact same sanitizer fix.
- Changing the structured logger or `WarnCtx`/`InfoCtx` API.
- Dismissing alerts via the UI as the primary mechanism — the pipeline's dismiss path exits non-zero (dismiss-only fix loops); source sanitization is the durable route. A human may dismiss any residual that genuinely can't be modeled, with written justification.

## Files In Scope
- `features/controller/api/handlers_jobs.go`
- `features/controller/api/handlers_workflows.go`
- `features/reports/provider/provider.go`

## Dependencies
None

## Acceptance Criteria
- [ ] Open `go/log-injection` code-scanning alerts #1031, #1032, #1006, #1011, #1016, #1056 are resolved (source-level sanitization); `gh api repos/cfg-is/cfgms/code-scanning/alerts?state=open --jq '[.[]|select(.rule.id=="go/log-injection")]|length'` shows those six no longer present after the develop scan.
- [ ] The sanitization uses the exact sequential-reassignment `strings.ReplaceAll` pattern documented above (verified against a live scan per site, not assumed from a similar-looking existing call).
- [ ] `handlers_jobs.go:146`'s real taint source is traced (via `execErr`/struct-field over-tainting, not just re-sanitizing `jobID`) before applying the fix to the correct variable.
- [ ] [REQUIRED TEST] `features/controller/api/handlers_jobs_test.go` adds a test covering the `handleCreateJob` error-execution log at `handlers_jobs.go:146` (e.g. `TestHandleCreateJob_ExecutorError_LogValueSanitized`) that asserts an `execErr` (or whichever value is confirmed to carry the taint after tracing) containing `\n`/`\r` is stripped in the logged field and a normal error message passes through unchanged.
- [ ] Docs — N/A (internal logging hardening, no product-shape change).
- [ ] `make test-complete` passes.

### PR DESCRIPTION
**Pull request by jrdnr**
## Summary

- Apply sequential-reassignment `strings.ReplaceAll` sanitization (CodeQL `ReplaceSanitizer` pattern) to 6 open `go/log-injection` alerts in `handlers_jobs.go`, `handlers_workflows.go`, and `reports/provider/provider.go`
- Each site also calls `logging.SanitizeLogValue()` for full C0/C1/DEL stripping (defence-in-depth)
- Add `jobExecutor` interface in `handlers_jobs.go` to decouple test injection from `*batchjob.RollingBatchExecutor`
- Add required AC test `TestHandleCreateJob_ExecutorError_LogValueSanitized` plus 8 new provider tests (GetTrendData, calculateComplianceScore, calculateRiskLevel)
- Fix monitoring collectors to collect once immediately on start, eliminating a timing-dependent flaky test

## Alert locations resolved

| Alert | File | Line |
|-------|------|------|
| #1031 | `features/controller/api/handlers_jobs.go` | 77 |
| #1032 | `features/controller/api/handlers_jobs.go` | 146 |
| #1006 | `features/controller/api/handlers_workflows.go` | 411 |
| #1011 | `features/controller/api/handlers_workflows.go` | 461 |
| #1016 | `features/controller/api/handlers_workflows.go` | 490 |
| #1056 | `features/reports/provider/provider.go` | 57 |

## Test plan

- [x] `make test` — passes
- [x] `make test-commit` — passes
- [x] `make check-architecture` — no violations
- [x] `make security-scan` — no critical/high findings
- [x] `make test-agent-complete` — exit 0 (all CI checks covered)
- [x] story-review workflow: 2 rounds, 1 fix round, `passed: true`
- [x] `TestHandleCreateJob_ExecutorError_LogValueSanitized` — both subtests pass

Fixes #2673

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by jrdnr** [comment]
## Acceptance Review — FAIL

**Story:** #2673 — security: clear go/log-injection CodeQL FP alerts (controller-api, reports-provider)
**Fix cycle:** First review

---

### Acceptance Criteria

- [x] **AC1** — Open `go/log-injection` alerts #1031, #1032, #1006, #1011, #1016, #1056 resolved via source-level sanitization. Code implementation is correct at all six sites (see Code-Reference Verification). Note: alerts remain in `state=open` on develop pre-merge, which is expected — they can only clear after this PR merges and CodeQL re-scans develop. AC condition "after the develop scan" is a post-merge verification; implementation is complete.
- [x] **AC2** — Sequential-reassignment `strings.ReplaceAll` pattern applied correctly at all six sites (verified by file read, not diff alone).
- [x] **AC3** — `handlers_jobs.go:146` taint traced to `execErr` (not `jobID`). PR comment at PR-HEAD:157 explains the taint path; `safeExecErr := execErr.Error()` + sequential reassignment is the correct fix.
- [x] **AC4** — `TestHandleCreateJob_ExecutorError_LogValueSanitized` added to `handlers_jobs_test.go` with both subtests (`newlines_stripped` and `clean_error_passes_through`). Both confirm `\n`/`\r` in `execErr` are stripped in the logged `error` field and clean errors pass through unchanged.
- [x] **AC5** — Docs N/A (internal logging hardening, no product-shape change).
- [x] **AC6** — `make test-complete` passes: unit-tests ✅, integration-tests ✅, Build Gate ✅.

---

### Code-Reference Verification

| AC # | Reference | Expected | Actual | Pass/Fail |
|------|-----------|----------|--------|-----------|
| 1 | `handlers_jobs.go` alert #1031 (orig line 77 → PR-HEAD ~81–88) | `safeSelector` via sequential ReplaceAll before log call | Lines 81–83: `safeSelector := logging.SanitizeLogValue(req.Selector)` then `strings.ReplaceAll(\n)` then `strings.ReplaceAll(\r)`. Log at line 88 uses `safeSelector`. | PASS |
| 1 | `handlers_jobs.go` alert #1032 (orig line 146 → PR-HEAD ~159–163) | `execErr` taint sanitized, not `jobID` | `safeExecErr := execErr.Error()` at 159, sequential ReplaceAll at 160–161, log at 163 uses `safeExecErr`. Correct taint variable. | PASS |
| 1 | `handlers_workflows.go` alert #1006 (orig line 411 → PR-HEAD 409–418) | `nameForLog`/`execIDForLog` via sequential ReplaceAll | Lines 409–414: both vars receive sequential ReplaceAll. Log at 418 uses sanitized vars. | PASS |
| 1 | `handlers_workflows.go` alert #1011 (orig line 461 → PR-HEAD 462–474) | same pattern, cancelExecution | Lines 462–467: both vars receive sequential ReplaceAll. Log at 474 uses sanitized vars. | PASS |
| 1 | `handlers_workflows.go` alert #1016 (orig line 490 → PR-HEAD ~503) | "Failed to cancel execution" log uses sanitized vars | PR-HEAD:503 `h.logger.Error("Failed to cancel execution", "name", nameForLog, ...)` — `nameForLog`/`execIDForLog` sanitized by cancelExecution block at lines 462–467. | PASS |
| 1 | `reports/provider/provider.go` alert #1056 (orig line 57 → PR-HEAD 60–63) | `safeDeviceID` via sequential ReplaceAll | Lines 60–62: `safeDeviceID := logging.SanitizeLogValue(deviceID)` then both ReplaceAll. Log at 63 uses `safeDeviceID`. | PASS |
| 3 | `handlers_jobs.go:146` taint source | `execErr`, not `jobID` | `safeExecErr` built from `execErr.Error()` — correct variable. Comment at PR-HEAD:157 traces the taint path. | PASS |
| 4 | `TestHandleCreateJob_ExecutorError_LogValueSanitized` in `handlers_jobs_test.go` | Function definition present | Line 500: `func TestHandleCreateJob_ExecutorError_LogValueSanitized(t *testing.T)`, subtests `newlines_stripped` and `clean_error_passes_through`. | PASS |
| ALL | Banned-phrase scan (`for now`, `simulate`, `would implement`, `tracked internally`, `placeholder implementation`, `In a real implementation`, `In a full implementation`) | 0 matches in all named files | 0 matches in all three production files and in diff additions. | PASS |

---

### Findings

| # | Severity | File | Description |
|---|----------|------|-------------|
| 1 | high | `features/controller/api/handlers_jobs.go:77` | **GHAS: go/log-injection** — `pr-security-findings.sh` reports open alert at line 77 on an added line. **Classification: likely-false-positive.** Analysis: The develop-branch alert #1031 was recorded at develop:77 (the old nested-ReplaceAll safeSelector assignment, since deleted). The PR adds a comment at PR-HEAD:77 (`// safeSelector strips control characters...`). The line-number intersection fires because develop alert line 77 = PR-added line 77, but these reference different code in different file states. PR-HEAD:77 is a comment — not a log-injection sink; CodeQL cannot flag a comment. The real vulnerable code was removed and replaced with the correct sequential-reassignment pattern at PR-HEAD:81–83. Alert will clear on develop re-scan after merge. |
| 2 | high | `features/controller/api/handlers_workflows.go:411` | **GHAS: go/log-injection** — open alert at line 411 on an added line. **Classification: likely-false-positive.** Analysis: The develop-branch alert #1006 was at develop:411 (old `nameForLog := logging.SanitizeLogValue(name)` log call site). The PR adds a sanitization reassignment at PR-HEAD:411 (`nameForLog = strings.ReplaceAll(nameForLog, "\r", "_")`). A `strings.ReplaceAll` call is not a log-injection sink. Line-number coincidence: 6 new lines added in the getExecution block shifted code forward, landing the second ReplaceAll at position 411, which matches the old develop alert line. |
| 3 | high | `features/controller/api/handlers_workflows.go:461` | **GHAS: go/log-injection** — open alert at line 461 on an added line. **Classification: likely-false-positive.** Analysis: The develop-branch alert #1011 was at develop:461 (old cancelExecution log call site). The PR adds a comment at PR-HEAD:461 (`// these values as sanitized (logging.SanitizeLogValue alone is not modelled by CodeQL).`). A comment cannot be a log-injection sink. Same line-number coincidence as finding #2. |

**Root cause of all three FPs:** The GHAS helper intersects open develop-branch alert line numbers with PR-added line numbers in the new file layout. When a PR fixes an alert site by (a) removing the vulnerable code and (b) inserting new safe code that occupies the same absolute line number as the old alert — due to lines added earlier in the file shifting positions — the intersection fires on safe added code. These three alerts will naturally close once this PR merges and `develop` is re-scanned by CodeQL.

**Escalation:** Per review policy, I cannot dismiss these alerts. Routing to the founder for a human dismissal decision on alerts #1031, #1006, #1011 in GitHub. Alternatively, if the alerts close automatically post-merge (expected), a re-dispatch of this reviewer after merge confirmation would yield PASS.

---

### CI Status

All required checks passing:
- `unit-tests` ✅
- `integration-tests` ✅
- `Build Gate` ✅
- `security-deployment-gate` — skipping (conditional on main-targeting PRs; not required for develop PRs)
- `CodeQL Analysis (go)` ✅

---

### Verdict

**FAIL — Fix required (first review).**

All acceptance criteria are met at the code level. The fail is driven exclusively by three GHAS `go/log-injection` findings that are assessed as **likely false positives** from a line-number intersection artifact in the security helper. The code changes are correct and the six target alerts are properly addressed.

**Recommended resolution (no code change needed):**
A human with write access should dismiss alerts #1031, #1006, #1011 in GitHub's Security tab with justification "Fixed by PR #2676 — sequential-reassignment sanitization applied; alert will close on develop re-scan post-merge." After dismissal, re-dispatching this acceptance reviewer should yield PASS.

**Comment by jrdnr** [comment]
## Acceptance Review — FAIL

> **Review cycle:** Fix cycle (second review — status was `Fix`). This failure escalates to **Blocked + founder assignment**.

---

### Acceptance Criteria

- [x] **AC1** — Open `go/log-injection` alerts #1031, #1032, #1006, #1011, #1016, #1056 resolved via source-level sanitization: sequential-reassignment fix is present at all 6 sites. Alerts remain open on develop until post-merge CodeQL re-scan (expected); the code change is correct.
- [x] **AC2** — Sequential-reassignment `strings.ReplaceAll` pattern used at every flagged site (`handlers_jobs.go`, `handlers_workflows.go`, `provider.go`) — verified in PR HEAD files.
- [x] **AC3** — `handlers_jobs.go:146` taint traced to `execErr.Error()` (not `jobID`); PR sanitizes `safeExecErr` correctly via `execErr.Error()` before logging.
- [x] **AC4 [REQUIRED TEST]** — `TestHandleCreateJob_ExecutorError_LogValueSanitized` present in `handlers_jobs_test.go` with both subtests (`newlines_stripped`, `clean_error_passes_through`). CI passes.
- [x] **AC5** — Docs N/A (internal logging hardening, no product-shape change).
- [x] **AC6** — `make test-complete` passes (all CI checks green).

---

### Code-Reference Verification

| AC # | Reference | Expected | Actual | Pass/Fail |
|------|-----------|----------|--------|-----------|
| 1 | Alert #1031 — `handlers_jobs.go:77` (old) | sequential-reassignment fix at log site | new-file line 77 is fix comment; `safeSelector` sanitized via sequential form at ~line 82 | PASS |
| 1 | Alert #1032 — `handlers_jobs.go:146` (old) | `safeExecErr` from `execErr.Error()` sanitized | `safeExecErr = execErr.Error()` + sequential ReplaceAll at ~line 163 | PASS |
| 1 | Alert #1006 — `handlers_workflows.go:411` (old) | `nameForLog`/`execIDForLog` via sequential-reassignment | new-file line 411 is `nameForLog = strings.ReplaceAll(...)` (the fix itself) | PASS |
| 1 | Alert #1011 — `handlers_workflows.go:461` (old) | cancelExecution same pattern | sequential-reassignment for `nameForLog`/`execIDForLog` + `safeErrStr` present | PASS |
| 1 | Alert #1016 — `handlers_workflows.go:490` (old) | error sanitized in cancelExecution | `safeErrStr` pattern applied before `h.logger.Error("Execution not found for cancel", ...)` | PASS |
| 1 | Alert #1056 — `provider.go:57` (old) | `safeDeviceID` + `safeErr` sequential form | `safeDeviceID = strings.ReplaceAll(...)` + `safeErr = strings.ReplaceAll(...)` at ~lines 67-73 | PASS |
| 4 | `TestHandleCreateJob_ExecutorError_LogValueSanitized` in `handlers_jobs_test.go` | required test present with both subtests | present, both subtests (`newlines_stripped`, `clean_error_passes_through`) | PASS |
| ban | grep `for now\|simulate\|would implement\|tracked internally\|placeholder` in diff additions | 0 matches | 0 matches | PASS |

---

### Findings

| # | Severity | File | Description |
|---|----------|------|-------------|
| 1 | High | `features/controller/api/handlers_jobs.go:77` | **GHAS `go/log-injection` (alert #1031) — `pr-security-findings.sh` output, classification: likely-false-positive.** The open develop alert at line 77 intersects with the PR's added new-file lines. At new-file line 77 the PR has added a comment (`// safeSelector strips control characters...`) — the fix itself. The alert tracks the pre-fix broken code at develop line 77; once this PR merges and CodeQL re-scans develop the alert should auto-close. **Cannot dismiss or merge on agent authority regardless of FP read — human action required.** |
| 2 | High | `features/controller/api/handlers_workflows.go:411` | **GHAS `go/log-injection` (alert #1006) — `pr-security-findings.sh` output, classification: likely-false-positive.** The open develop alert at line 411 intersects with the PR's added new-file lines. At new-file line 411 the PR has `nameForLog = strings.ReplaceAll(nameForLog, "\n", "_")` — part of the sequential-reassignment fix for that exact alert. Same root cause as Finding #1: develop's alert line numbers shifted into the PR's added-line range. Alert should auto-close post-merge. **Human dismissal or merge-then-rescan required.** |

---

### CI Status

All required checks passing:
- `unit-tests` ✓
- `integration-tests` ✓
- `Build Gate` ✓
- `security-deployment-gate` ✓
- `CodeQL Analysis (go)` ✓ (advisory mode — Pass 2 of `pr-security-findings.sh` caught open develop alerts; see Findings)

---

### Verdict

**FAIL — Blocked — escalated to founder.**

All AC checkboxes are met and all Code-Reference Verification rows pass. The blocking findings (#1 and #2) are **likely false positives** from the `pr-security-findings.sh` Pass 2 intersection: the develop branch's open alerts at lines 77 and 411 coincidentally match added-line numbers in the PR's new-file numbering after code shifts. The code at those new-file positions is the sanitization fix, not the vulnerability.

**Recommended founder actions (either unblocks):**

Option A — **Dismiss in GitHub:** In the Security → Code scanning tab, dismiss alerts #1031 and #1006 with reason: *"Fixed in PR #2676; alert location is on develop pre-fix code, will auto-close on next scan post-merge."* Then re-dispatch the acceptance reviewer — the `pr-security-findings.sh` Pass 2 respects human dismissal (`state=open` → dismissed alerts drop out).

Option B — **Merge manually:** Since all AC, CI, and code-review checks are clean, a manual `gh pr merge --squash 2676` (bypassing the acceptance gate) is also appropriate given the FP analysis. The develop CodeQL scan post-merge will close all 6 target alerts.

**Comment by jrdnr** [comment]
## Acceptance Review — PASS

**Story:** #2673 — security: clear go/log-injection CodeQL FP alerts (controller-api, reports-provider)
**Review cycle:** This review (status was `Blocked`; fresh review after founder-supervised fix commits)

---

### Acceptance Criteria

- [x] **AC 1** — Open `go/log-injection` alerts #1031, #1032, #1006, #1011, #1016, #1056 are resolved: All 6 dismissed by `jrdnr` on 2026-07-16 with written justification "Fixed in PR #2676 (#2673) — sanitization verified correct at this site. Alert anchored to develop's pre-fix line; auto-closes on post-merge rescan." Source-level fix is implemented in the PR. `?state=open` query returns 0 for all 6 story alerts (4 remaining open alerts are in `features/workflow/providers.go`, outside this story's scope).
- [x] **AC 2** — Sanitization uses the exact sequential-reassignment `strings.ReplaceAll` pattern at all sites: `handlers_jobs.go` (safeSelector at lines 82-83, safeParseErr at 89-90, safeExecErr at 164-165), `handlers_workflows.go` (nameForLog+execIDForLog at each handler, safeErrStr for error paths), `provider.go` (safeDeviceID at 68-69, safeErr at 71-72, and same pattern in GetDeviceStats path at 140-144).
- [x] **AC 3** — `handlers_jobs.go:146` taint source traced: comment correctly identifies "execErr may embed job.Selector (user-tainted) via executor error messages" — `jobID` (uuid, not user-tainted) is not sanitized; `safeExecErr` is. Correct.
- [x] **AC 4 [REQUIRED TEST]** — `TestHandleCreateJob_ExecutorError_LogValueSanitized` added in `handlers_jobs_test.go` at line 512 with both subtests (`newlines_stripped`, `clean_error_passes_through`). Uses real components (`errorCapturingLogger`, `errBatchJobExecutor`) with no mocks.
- [x] **AC 5** — Docs N/A (internal logging hardening, no product-shape change). Confirmed.
- [x] **AC 6** — `make test-complete` passes: all required CI checks pass (unit-tests, integration-tests, Build Gate, security-deployment-gate).

### Code-Reference Verification

| AC # | Reference | Expected | Actual | Pass/Fail |
|------|-----------|----------|--------|-----------|
| 1 | Alert #1031 — handlers_jobs.go (safeSelector log) | state != open | state=dismissed, dismissed_by=jrdnr, code fix present | **PASS** |
| 1 | Alert #1032 — handlers_jobs.go (execErr log) | state != open | state=dismissed, dismissed_by=jrdnr, code fix present | **PASS** |
| 1 | Alert #1006 — handlers_workflows.go:411 area | state != open | state=dismissed, dismissed_by=jrdnr, code fix present | **PASS** |
| 1 | Alert #1011 — handlers_workflows.go:461 area | state != open | state=dismissed, dismissed_by=jrdnr, code fix present | **PASS** |
| 1 | Alert #1016 — handlers_workflows.go:490 area | state != open | state=dismissed, dismissed_by=jrdnr, code fix present | **PASS** |
| 1 | Alert #1056 — provider.go:57 area | state != open | state=dismissed, dismissed_by=jrdnr, code fix present | **PASS** |
| 2 | Sequential ReplaceAll @ handlers_jobs.go | `safeX = ReplaceAll(safeX, "\n", "_"); safeX = ReplaceAll(safeX, "\r", "_")` | Lines 82-83 (safeSelector), 89-90 (safeParseErr), 164-165 (safeExecErr) — exact pattern present | **PASS** |
| 2 | Sequential ReplaceAll @ handlers_workflows.go | Same pattern for nameForLog+execIDForLog | Lines 409-414, 467-472 for both vars; safeErrStr at each error path | **PASS** |
| 2 | Sequential ReplaceAll @ provider.go | Same pattern for safeDeviceID + safeErr | Lines 68-72 (GetDNAData), 140-144 (GetDeviceStats) | **PASS** |
| 3 | Taint source trace @ handlers_jobs.go:146 | execErr (not jobID) identified as taint carrier | Code comment confirms: "execErr may embed job.Selector (user-tainted) via executor error messages"; safeExecErr used in log, jobID unmodified (correct — uuid, not user-tainted) | **PASS** |
| 4 | `TestHandleCreateJob_ExecutorError_LogValueSanitized` in handlers_jobs_test.go | New function definition present | Found at line 512; two subtests covering dirty and clean error cases | **PASS** |

### Findings

None.

### CI Status

All required checks passing:
- `unit-tests` ✅
- `integration-tests` ✅  
- `Build Gate` ✅
- `security-deployment-gate` ✅

GHAS (Phase 2.1): no open alerts on PR-added lines — helper returned empty output.

### Additional Notes

- The `jobExecutor` interface added in `handlers_jobs.go` and the `dnaHistory` interface added in `provider.go` are minimal, self-contained, and correctly enable test injection without cross-package dependency. No architecture concern.
- The `features/monitoring/collectors.go` change (collect once immediately on start) is a legitimate timing fix that eliminates flaky test behaviour. No concern.
- `server.go` field type change (`*batchjob.RollingBatchExecutor` → `jobExecutor`) correctly propagates the interface to the `SetBatchJobExecutor` setter.
- 4 remaining open `go/log-injection` alerts (#1122–#1125 in `features/workflow/providers.go`) are out of scope for this story.

### Verdict

Auto-merging — all acceptance criteria met, zero findings.

**Comment by jrdnr** [comment]
## CI red: silent semantic merge conflict with #2702 (workflow.NewEngine signature)

`unit-tests` is failing with a real compile error, not a review-comment gap:

```
features/controller/api/handlers_workflows_test.go:807:97: not enough arguments in call to workflow.NewEngine
features/controller/api/handlers_workflows_test.go:836:97: not enough arguments in call to workflow.NewEngine
```

**Root cause:** PR #2702 (merged to `develop` after this branch was created) added two new
required parameters to `workflow.NewEngine` — `setHARoleExecutor SetHARoleStepExecutor` and
`moveResourceToClusterExecutor MoveResourceToClusterStepExecutor` — bringing it from 5 params
to 7 (`features/workflow/engine.go:83`). Git's text-level merge/rebase does not flag this
because it's a semantic conflict, not a textual one: this branch's copy of
`handlers_workflows_test.go` still calls the old 5-arg form at **5 call sites**
(lines 36, 558, 590, 807, 836 in this branch's current version of the file).

**Required fix:** update all 5 `workflow.NewEngine(...)` call sites in
`features/controller/api/handlers_workflows_test.go` to the current 7-parameter signature,
matching the pattern already used everywhere else on `develop` (e.g.
`features/controller/api/registration_hook_test.go:95`,
`features/controller/api/server_lazy_routes_test.go:34,136`,
`features/workflow/trigger/controller_factory_test.go:73`) — simply append two more
`nil` arguments at the end of each existing call (test call sites pass `nil` for the
executor params already, so `..., nil, nil)` at the end of each is sufficient; no other
logic changes are needed).

This is the ONLY thing blocking this PR right now — the previous fix-cycle commit
(6d270fde) addressed unrelated review comments (calculateDeviceStats/log-sanitization) and
did not touch this file. Please rebase onto current `origin/develop` first (to confirm you're
looking at develop's real current signature) and then fix these 5 call sites.

**Comment by jrdnr** [comment]
## Acceptance Review — PASS

### Acceptance Criteria

- [x] **AC1** — Open `go/log-injection` alerts #1031, #1032, #1006, #1011, #1016, #1056 resolved: all six are in `state=dismissed` with `dismissed_reason=false_positive`; the 7 remaining open `go/log-injection` alerts are all in unrelated files (`features/workflow/providers.go`, `features/tenant/manager.go`). Source-level sanitization is applied at every site so CodeQL will auto-close these on the post-merge develop scan.
- [x] **AC2** — Sequential-reassignment `strings.ReplaceAll` pattern used at all six sites: `safeSelector = strings.ReplaceAll(safeSelector, "\n", "_")` / `strings.ReplaceAll(safeSelector, "\r", "_")` in handlers_jobs.go:82-83; `safeExecErr = ...` x2 in handlers_jobs.go:164-165; `nameForLog = ...` / `execIDForLog = ...` x2 each in handlers_workflows.go:410-414 (get path) and 470-474 (cancel path); `safeDeviceID = ...` x2 in provider.go:68-69.
- [x] **AC3** — `handlers_jobs.go:146` taint traced correctly: `jobID` (`uuid.New().String()`) is captured before the struct (line 127) so it is not tainted by `job.Selector`; the real taint carrier is `execErr` from `executor.Execute`, which may embed `job.Selector` via error formatting. Fix sanitizes `execErr` into `safeExecErr` at lines 163-165.
- [x] **AC4** — `TestHandleCreateJob_ExecutorError_LogValueSanitized` in `handlers_jobs_test.go` at line 512: two subtests (`newlines_stripped`, `clean_error_passes_through`) using a real `errorCapturingLogger` (implements `logging.Logger`, not a mock) and `errBatchJobExecutor` satisfying the `jobExecutor` interface. Asserts `\n`/`\r` stripped and error text preserved.
- [x] **AC5** — Docs N/A: internal logging hardening, no product-shape change. Confirmed no doc changes in PR.
- [x] **AC6** — `make test-complete` passes: all CI checks green (unit-tests 9-min real run passed; Build Gate, security-deployment-gate via PR-time stubs; CodeQL Analysis 5m31s passed).

### Code-Reference Verification

| AC # | Reference | Expected | Actual | Pass/Fail |
|------|-----------|----------|--------|-----------|
| 1 | Alert #1031 @ handlers_jobs.go:77 (safeSelector log) | sequential ReplaceAll on safeSelector | handlers_jobs.go:82-83 — `safeSelector = strings.ReplaceAll(safeSelector, "\n", "_")` + `"\r"` variant | PASS |
| 1 | Alert #1032 @ handlers_jobs.go:146 (execErr log) | sequential ReplaceAll on execErr taint, not jobID | handlers_jobs.go:163-165 — `safeExecErr = execErr.Error()` + two ReplaceAll reassignments | PASS |
| 1 | Alert #1006 @ handlers_workflows.go:411 | sequential ReplaceAll on nameForLog + execIDForLog | handlers_workflows.go:410-414 — four reassignments (two per variable) | PASS |
| 1 | Alert #1011 @ handlers_workflows.go:461 | sequential ReplaceAll on nameForLog + execIDForLog (cancel path) | handlers_workflows.go:470-474 — four reassignments | PASS |
| 1 | Alert #1016 @ handlers_workflows.go:490 | sequential ReplaceAll on cancel-path log | handlers_workflows.go:488: `h.logger.Error("Execution not found for cancel", ...)` using sanitized variables from lines 469-474 | PASS |
| 1 | Alert #1056 @ provider.go:57 | sequential ReplaceAll on safeDeviceID | provider.go:68-69 — `safeDeviceID = strings.ReplaceAll(...)` x2 | PASS |
| 2 | sequential-reassignment pattern (all sites) | two top-level reassignments, no nested calls | all sites use `x = ReplaceAll(x, "\n", ...)` then `x = ReplaceAll(x, "\r", ...)` | PASS |
| 3 | handlers_jobs.go:146 taint tracing | execErr (not jobID) is the taint carrier | jobID captured before job struct (line 127); execErr sanitized into safeExecErr; comment confirms tracing | PASS |
| 4 | TestHandleCreateJob_ExecutorError_LogValueSanitized @ handlers_jobs_test.go | test present, real implementation, two subtests | found at line 512; errorCapturingLogger + errBatchJobExecutor are real components; asserts stripping and passthrough | PASS |
| 5 | grep banned phrases in all three in-scope files | 0 matches | 0 matches across handlers_jobs.go, handlers_workflows.go, provider.go | PASS |
| 6 | GHAS findings (pr-security-findings.sh) | empty output | empty — no new open GHAS findings on PR additions | PASS |

### Findings

None.

**Informational (non-blocking):** `features/monitoring/collectors.go` includes a one-line change (`sm.collectMetrics(ctx)` immediately before the ticker loop) that is outside the story's "Files In Scope" list. This is a legitimate fix for timing-dependent test flakiness (confirmed by PR body) and introduces no security or architecture concern; it does not affect the CodeQL fix surface. No action required — noting for visibility only.

### CI Status

All required checks passing:
- `unit-tests` — passed (9-min real run, fast-unit-tests step green)
- `integration-tests` — passed (PR-time stub; real run in merge queue)
- `Build Gate` — passed
- `security-deployment-gate` — passed (PR-time stub; real scan in merge queue)
- `CodeQL Analysis (go)` — passed (5m31s real scan)
- `gosec-scan`, `nancy-scan`, `staticcheck-scan`, `zizmor` — all passed
- GHAS findings helper: empty (no new open alerts on PR additions)

### Verdict

Auto-merged — all acceptance criteria met, all code-reference checks PASS, no findings.
